package com.soho.ssc.greendao;

import android.database.Cursor;
import android.database.sqlite.SQLiteStatement;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.Property;
import org.greenrobot.greendao.internal.DaoConfig;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.database.DatabaseStatement;

import com.soho.ssc.domain.HistoryVideo;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table "HISTORY_VIDEO".
*/
public class HistoryVideoDao extends AbstractDao<HistoryVideo, Long> {

    public static final String TABLENAME = "HISTORY_VIDEO";

    /**
     * Properties of entity HistoryVideo.<br/>
     * Can be used for QueryBuilder and for referencing column names.
     */
    public static class Properties {
        public final static Property Id = new Property(0, long.class, "id", true, "_id");
        public final static Property Name = new Property(1, String.class, "name", false, "NAME");
        public final static Property Poster = new Property(2, String.class, "poster", false, "POSTER");
        public final static Property Updated_time = new Property(3, String.class, "updated_time", false, "updated_time");
        public final static Property Is_pro = new Property(4, boolean.class, "is_pro", false, "IS_PRO");
        public final static Property Current = new Property(5, int.class, "current", false, "CURRENT");
    }


    public HistoryVideoDao(DaoConfig config) {
        super(config);
    }
    
    public HistoryVideoDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
    }

    /** Creates the underlying database table. */
    public static void createTable(Database db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "\"HISTORY_VIDEO\" (" + //
                "\"_id\" INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL ," + // 0: id
                "\"NAME\" TEXT UNIQUE ," + // 1: name
                "\"POSTER\" TEXT," + // 2: poster
                "\"updated_time\" TEXT," + // 3: updated_time
                "\"IS_PRO\" INTEGER NOT NULL ," + // 4: is_pro
                "\"CURRENT\" INTEGER NOT NULL );"); // 5: current
    }

    /** Drops the underlying database table. */
    public static void dropTable(Database db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "\"HISTORY_VIDEO\"";
        db.execSQL(sql);
    }

    @Override
    protected final void bindValues(DatabaseStatement stmt, HistoryVideo entity) {
        stmt.clearBindings();
        stmt.bindLong(1, entity.getId());
 
        String name = entity.getName();
        if (name != null) {
            stmt.bindString(2, name);
        }
 
        String poster = entity.getPoster();
        if (poster != null) {
            stmt.bindString(3, poster);
        }
 
        String updated_time = entity.getUpdated_time();
        if (updated_time != null) {
            stmt.bindString(4, updated_time);
        }
        stmt.bindLong(5, entity.getIs_pro() ? 1L: 0L);
        stmt.bindLong(6, entity.getCurrent());
    }

    @Override
    protected final void bindValues(SQLiteStatement stmt, HistoryVideo entity) {
        stmt.clearBindings();
        stmt.bindLong(1, entity.getId());
 
        String name = entity.getName();
        if (name != null) {
            stmt.bindString(2, name);
        }
 
        String poster = entity.getPoster();
        if (poster != null) {
            stmt.bindString(3, poster);
        }
 
        String updated_time = entity.getUpdated_time();
        if (updated_time != null) {
            stmt.bindString(4, updated_time);
        }
        stmt.bindLong(5, entity.getIs_pro() ? 1L: 0L);
        stmt.bindLong(6, entity.getCurrent());
    }

    @Override
    public Long readKey(Cursor cursor, int offset) {
        return cursor.getLong(offset + 0);
    }    

    @Override
    public HistoryVideo readEntity(Cursor cursor, int offset) {
        HistoryVideo entity = new HistoryVideo( //
            cursor.getLong(offset + 0), // id
            cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1), // name
            cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2), // poster
            cursor.isNull(offset + 3) ? null : cursor.getString(offset + 3), // updated_time
            cursor.getShort(offset + 4) != 0, // is_pro
            cursor.getInt(offset + 5) // current
        );
        return entity;
    }
     
    @Override
    public void readEntity(Cursor cursor, HistoryVideo entity, int offset) {
        entity.setId(cursor.getLong(offset + 0));
        entity.setName(cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1));
        entity.setPoster(cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2));
        entity.setUpdated_time(cursor.isNull(offset + 3) ? null : cursor.getString(offset + 3));
        entity.setIs_pro(cursor.getShort(offset + 4) != 0);
        entity.setCurrent(cursor.getInt(offset + 5));
     }
    
    @Override
    protected final Long updateKeyAfterInsert(HistoryVideo entity, long rowId) {
        entity.setId(rowId);
        return rowId;
    }
    
    @Override
    public Long getKey(HistoryVideo entity) {
        if(entity != null) {
            return entity.getId();
        } else {
            return null;
        }
    }

    @Override
    public boolean hasKey(HistoryVideo entity) {
        throw new UnsupportedOperationException("Unsupported for entities with a non-null key");
    }

    @Override
    protected final boolean isEntityUpdateable() {
        return true;
    }
    
}
